### ISSUE TITLE
problem testing a UCSC file

### ISSUE THREAD

**Issue by childers** [NCBI-Hackathons/Master_gff3_parser#7]
```shell
$ time  seqconv convert --ref felCat4 --out rs cat_felCat4_UCSC_2008 
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/003/115/GCA_000003115.1_catChrV17e/GCA_000003115.1_catChrV17e_assembly_report.txt
Converting from None to rsStarting Conversion
Cannot convert id: exon
Traceback (most recent call last):
  File "/usr/local/bin/seqconv", line 11, in <module>
    load_entry_point('seqconv==0.0.1', 'console_scripts', 'seqconv')()
  File "/usr/local/lib/python2.7/site-packages/seqconv-0.0.1-py2.7.egg/cli/command.py", line 98, in main
    comm()
  File "/usr/local/lib/python2.7/site-packages/seqconv-0.0.1-py2.7.egg/cli/command.py", line 52, in __init__
    getattr(self, args.command)()
  File "/usr/local/lib/python2.7/site-packages/seqconv-0.0.1-py2.7.egg/cli/command.py", line 94, in convert
    id_to=args.out)
  File "/usr/local/lib/python2.7/site-packages/seqconv-0.0.1-py2.7.egg/cli/assembly.py", line 294, in converter
    except (KeyboardInterrupt, SystemExit, BrokenPipeError):
NameError: global name 'BrokenPipeError' is not defined

real	0m43.185s
user	0m1.913s
sys	0m0.183s

```

**Comment by childers** [comment]
appending .gtf to the file and rerunning, now getting a different error:
```text
$ time  seqconv convert --ref felCat4 --out rs cat_felCat4_UCSC_2008.gtf 
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/003/115/GCA_000003115.1_catChrV17e/GCA_000003115.1_catChrV17e_assembly_report.txt
Converting from None to rsStarting Conversion
Cannot convert id: chrM
No corresponding id for chrX from None
FORMAT detected: uc
real	0m25.489s
user	0m1.824s
sys	0m0.192s

```

**Comment by guilhemfaure** [comment]
@danielecook can you check the BrokenPipe with @childers ?
Thanks
